#Source->https://www.youtube.com/watch?v=pYhLEV-sRpY
#Improvements->
#
# Upgraded To Latest Version (3.9)
#
# Naming Formats
#    - image_db_<<<type>>>_<<<title>>>
#    - image_site_<<<type>>>_<<<title>>>
#
# New Image Names ->
#    Database->     image_db_mysql_abc
#    Site->         image_site_wp_abc
#    PhpMyAdmin->   image_site_pma_abc
#    Network->      network1_abc
#    Volume->       volume_db_data
#
#Changed Volume To "wp-content" directory
#
version: '3.9'

services:
  # Database
  image_db_mysql_abc:
    image: ${DB_IMAGE}
    volumes:
      - ${DB_LOCAL_PATH_OR_VOLUME}:${DB_DOCKER_PATH}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - ${NETWORK1_NAME}
  # phpmyadmin
  image_site_pma_abc:
    depends_on:
      - ${DB_IMAGE_NAME}
    image: ${PMA_IMAGE}
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - ${NETWORK1_NAME}
  # Wordpress Site
  image_site_wp_abc:
    depends_on:
      - ${DB_IMAGE_NAME}
    image: ${WP_IMAGE}
    ports:
      - ${WP_PORT}:80
    restart: always
    volumes:
      - ${WP_LOCAL_PATH}:${WP_DOCKER_PATH}
    environment:
      WORDPRESS_DB_HOST: ${DB_IMAGE_NAME}:${DB_PORT}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - ${NETWORK1_NAME}
networks:
  network1_abc:
volumes:
  volume_db_mysql_abc:
