#source->https://hub.docker.com/_/httpd
FROM httpd:2.4

#Common Commands

COPY ./public-html/ /usr/local/apache2/htdocs/

COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf

#Run your web traffic over SSL
COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf

#Update conf file
/usr/local/apache2/conf/httpd.conf

#...
#LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
#...
#LoadModule ssl_module modules/mod_ssl.so
#...
#Include conf/extra/httpd-ssl.conf
#...

#RUN sed -i \
#        -e 's/^#\(Include .*httpd-ssl.conf\)/\1/' \
#        -e 's/^#\(LoadModule .*mod_ssl.so\)/\1/' \
#        -e 's/^#\(LoadModule .*mod_socache_shmcb.so\)/\1/' \
#        conf/httpd.conf



#To run this.
# "docker build -t my-apache2 ."
# "docker run -dit --name my-running-app -p 8080:80 my-apache2"
# "docker run --rm httpd:2.4 cat /usr/local/apache2/conf/httpd.conf > my-httpd.conf"